### ISSUE TITLE
llvm->subleq compiler missing?

### ISSUE THREAD

**Issue by chrisdew** [purisc-group/purisc#3]
https://github.com/purisc-group/purisc/wiki#compiler mentions:

"We decided it would be easier to write our own backend ourselves which would parse the IR assembly file Clang generated and convert it into SUBLEQ assembly."

Is this code available in the repo?

**Comment by nulldozer** [comment]
Somehow we overlooked that (only one developer was working on it, so we weren't really using git). We will try to upload it within a few weeks

**Comment by chrisdew** [comment]
Thanks, I look forward to it.

**Comment by chrisdew** [comment]
Sorry to be impatient, but is there any news?

**Comment by nulldozer** [comment]
Thanks for the reminder, just merged it into the project

**Comment by chrisdew** [comment]
Thanks, I'll have a look at lunchtime.
